@startuml 

skinparam DefaultFontName PingFangSC-Regular

Mediator <-  Colleague
Mediator <|-- ConcreteMediator
Colleague <|-- ConcreteColleagueA
Colleague <|-- ConcreteColleagueB
ConcreteMediator -> ConcreteColleagueA
ConcreteMediator -> ConcreteColleagueB

@enduml