@startuml 

left to right direction
skinparam DefaultFontName PingFangSC-Regular

interface AbstractServiceA{
    + void operatorA()
}

interface AbstractServiceB{
    + void operatorB()
}

interface AbstractServiceC{
    + void operatorC()
}

class ConcreteService {
    + void operatorA()
    + void operatorB()
    + void operatorC()
}

ClientA -[hidden]right-> ClientB
ClientB -[hidden]right-> ClientC

ClientA -down-> AbstractServiceA
ClientB -down-> AbstractServiceB
ClientC -down-> AbstractServiceC
ConcreteService .up.|> AbstractServiceA
ConcreteService .up.|> AbstractServiceB
ConcreteService .up.|> AbstractServiceC
@enduml