@startuml 

left to right direction
skinparam DefaultFontName PingFangSC-Regular

interface AbstractService{
    + void operatorA()
    + void operatorB()
    + void operatorC()
}

class ConcreteService {
    + void operatorA()
    + void operatorB()
    + void operatorC()
}

ClientA -down-> AbstractService
ClientB -down-> AbstractService
ClientC -down-> AbstractService
ConcreteService .up.|> AbstractService

@enduml