@startuml 

skinparam DefaultFontName PingFangSC-Regular

Component <|-- Leaf
Component <|-- Composite
Component <--o Composite
Leaf <|-- LeafA
Leaf <|-- LeafB
Composite <|-- SubCompositeA
Composite <|-- SubCompositeB

@enduml
